### PR TITLE
News modal/backend

### PR DESCRIPTION
**Pull request by JiaqiWang18**
## Description
Create backend route for news modal
Add Ckeditor to admin

### CODE REVIEW

**Comment by JJamesWWang** [comment]
I think you have to add ckeditor to requirements_base.txt as well

**Comment by JJamesWWang** [comment]
Can you also replace the two migrations with just one

**Review by JJamesWWang — APPROVED** [review]

**Review by ruibrii — APPROVED** [review]

**Comment by JiaqiWang18** [comment]
should I merge this?

**Comment by JJamesWWang** [comment]
yeah you can

**Pull request merged**
