### PR TITLE
Refactor React components

### LINKED ISSUE #305: Display Info when user tries to disable settings not in correct order
It's confusing that you cannot disable some settings without first disabling the bottom ones. It makes sense but a message should be generated to inform the user of this in the case they try clicking on "Yes" and it doesn't work.

### PR DESCRIPTION
**Pull request by JiaqiWang18**
### Description - Describe your pull request
Refactor React class-based components and deprecated life-cycle methods to functional components and hooks. Update and create new test cases for each component

###  Checklist
- [x] 5 components done so far

closes #305

### CODE REVIEW

**Comment by JiaqiWang18** [comment]
I have created alerts for Facebook settings, please see the issues page for more detail. Those changes are ready to merge. I tested locally but it seems the CI is not running here?

**Comment by yesterd3v** [comment]
> I have created alerts for Facebook settings, please see the issues page for more detail. Those changes are ready to merge. I tested locally but it seems the CI is not running here?

You need to `git pull upstream prod` for this branch then re-push to get the CI to run

**Comment by yesterd3v** [comment]
@JiaqiWang18 I figured out why it wasn't running the CI, you can check out this #418 to see what I needed to update. Make sure you pull upstream again after that PR is merged.

**Comment by JiaqiWang18** [comment]
> @JiaqiWang18 I figured out why it wasn't running the CI, you can check out this #418 to see what I needed to update. Make sure you pull upstream again after that PR is merged.

Yes I see, need to update the branch filters since master was renamed to prod

**Comment by JiaqiWang18** [comment]
since I fixed [issue #305](https://github.com/jhuopensource/semesterly/issues/305)
PR is ready to be merged

**Review by yesterd3v — APPROVED** [review]
LGTM 🚀
Very thorough, the resolution to #305 looks suitable.
I'll merge, and I'll push to production if it passes the build checks.

**Pull request merged**
