### PR TITLE
answer readthedocs

### PR DESCRIPTION
**Pull request by JessieLuo30**

### CODE REVIEW

**Review by JJamesWWang — CHANGES_REQUESTED** [review]
Looks good! Can you revert the changes to readthedocs.md so that we can merge this?

**Comment by JJamesWWang** [comment]
If you could fix the merge conflict too that would be great

**Comment by JessieLuo30** [comment]
> If you could fix the merge conflict too that would be great

DONE

**Review by JJamesWWang — APPROVED** [review]
Looks good

**Pull request merged**
