### PR TITLE
Saturday sunday/add preference backend logic

### PR DESCRIPTION
**Pull request by JiaqiWang18**
## Description
Save user's preferences for showing weekends in the timetable
Creates an API endpoint to properly save timetable preferences
### Endpoint:
`user/timetables/<timetable id>/preferences/`
### Body:
```json
{
    "show_weekend": true/false,
    "has_conflict": true/false
}
```
### Response:
same as request body to be used to update the frontend

## Change Log
- [x] Add field `show_weekend` to `PersonalTimeTable`
- [x] Expose field to serializer for it to be accessible to frontend
- [x] Create a new view to toggle preferences
- [x] Add new testcases

### CODE REVIEW

**Comment by JiaqiWang18** [comment]
ignore the typos lol, don't want to force push

**Comment by yesterd3v** [comment]
Fix lint errors, and then it can probably be merged

**Review by JJamesWWang — APPROVED** [review]
Looks good

**Comment by yesterd3v** [comment]
@JJamesWWang @JiaqiWang18 
This has lint errors, it shouldn't have been merged.

**Comment by JJamesWWang** [comment]
@Boccca2014 it's not merged to develop so it's okay; I'll run the linter on the main feature branch

**Pull request merged**
