### PR TITLE
Created collapsible course list

### LINKED ISSUE #151: Create initial Advising Dashboard frontend components

### PR DESCRIPTION
**Pull request by miaboloix**
Made semester course list collapsible.

Screen Shot 2021-03-30 at 7 46 49 PM

Screen Shot 2021-03-30 at 7 46 58 PM

### CODE REVIEW

**Comment by miaboloix** [comment]
Screen Shot 2021-03-30 at 7 46 49 PM

Screen Shot 2021-03-30 at 7 46 58 PM

**Comment by JJamesWWang** [comment]
I get this error after pulling your branch (this is from a fresh docker-compose build as well) !(Webpack error)[https://cdn.discordapp.com/attachments/381244852555350017/826641502003527701/unknown.png]

**Comment by miaboloix** [comment]
> I get this error after pulling this branch (this is from a fresh docker-compose build as well) Webpack error

is `react-collapsible` inside your `package.json` ?

**Comment by JJamesWWang** [comment]
> is `react-collapsible` inside your `package.json` ?

Yeah, line 58 is `    "react-collapsible": "^2.8.3",`

**Comment by miaboloix** [comment]
> > is `react-collapsible` inside your `package.json` ?
> 
> Yeah, line 58 is ` "react-collapsible": "^2.8.3",`

**Update:** James was able to solve the issue by deleting `node_modules` and re-building with docker.

**Comment by Boccca2014** [comment]
I did the same thing James did, and it's throwing the same error. I even tried npm installing the package. It still failed.

**Comment by miaboloix** [comment]
> I tried the same thing James did, and it's throwing the same error. I even tried npm installing the package. It still failed.

did you npm install inside the docker container?

**Comment by Boccca2014** [comment]
That resolved it. Is there a reason this isn't being done automatically when building the docker container?

**Review by yesterd3v — APPROVED** [review]

**Review by JJamesWWang — APPROVED** [review]

**Pull request merged**
