### PR TITLE
Adding Spring 2021

### PR DESCRIPTION
**Pull request by miaboloix**

### CODE REVIEW

**Comment by alihacks** [comment]
The change look ok but we need to:
* Fix the build
* Add Spring 2021 to parsing to get data

**Comment by miaboloix** [comment]
> The change look ok but we need to:
> 
> * Fix the build
> * Add Spring 2021 to parsing to get data

I added Spring 2021 to the parser - do you know what this build error is about? -->
```
1.71s$` sudo -E apt-get -yq --allow-unauthenticated install google-chrome-stable
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  indicator-application libappindicator1 libappindicator3-1 libdbusmenu-glib4
  libdbusmenu-gtk3-4 libdbusmenu-gtk4 libindicator3-7 libindicator7
Use 'sudo apt autoremove' to remove them.
Recommended packages:
  libu2f-udev libvulkan1
The following packages will be upgraded:
  google-chrome-stable
1 upgraded, 0 newly installed, 0 to remove and 303 not upgraded.
Need to get 71.2 MB of archives.
After this operation, 54.8 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  google-chrome-stable
Authentication warning overridden.
Get:1 http://dl.google.com/linux/chrome/deb stable/main amd64 google-chrome-stable amd64 86.0.4240.183-1 [71.2 MB]
Fetched 71.2 MB in 0s (84.5 MB/s)
dpkg-deb: error: archive '/var/cache/apt/archives/google-chrome-stable_86.0.4240.183-1_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
dpkg: error processing archive /var/cache/apt/archives/google-chrome-stable_86.0.4240.183-1_amd64.deb (--unpack):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/google-chrome-stable_86.0.4240.183-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command "sudo -E apt-get -yq --allow-unauthenticated install google-chrome-stable" failed and exited with 100 during .
```

**Comment by alihacks** [comment]
@miaboloix did you try this one? https://askubuntu.com/questions/1065231/dpkg-deb-error-archive-has-premature-member-control-tar-xz-before-contr/1100361

**Comment by miaboloix** [comment]
Can't figure this out! I tried a few ways to install goog-chrome-stable version 79 but none of them worked. Do you think you could try debugging this for a bit? I believe the right syntax is something like `sudo -E apt-get -yq --allow-unauthenticated install google-chrome-stable=79.0.0` but I am getting an error that this version doesn't exist.

**Review by kristinyim — APPROVED** [review]

**Pull request merged**
