### PR TITLE
Refactor redux

### PR DESCRIPTION
**Pull request by JiaqiWang18**
### Description
Refactor redux and wire up new redux actions with react

### Tasks
- [ ] Refactor Redux reducers to RTK + Typescript
- [ ] Add tests

### CODE REVIEW

**Comment by JJamesWWang** [comment]
Looks great so far. Looks like tests are being run on this branch too. Keep it going 👍

**Comment by JJamesWWang** [comment]
Still looks good. This branch is getting a little big on changes; can you start making new branches and merge them to this branch for more refactor-redux work (when applicable)? Makes reviewing a little easier and also more clearer what you are doing.

**Comment by JiaqiWang18** [comment]
> Still looks good. This branch is getting a little big on changes; can you start making new branches and merge them to this branch for more refactor-redux work (when applicable)? Makes reviewing a little easier and also more clearer what you are doing.

I think this is a good idea but if I merge new branches to this one, I won't get features such as CI and code reviews because I am merging into my forked repo: [https://github.com/JiaqiWang18/semesterly/pull/4](https://github.com/JiaqiWang18/semesterly/pull/4)

I think I should merge the above branch into this one and merge this branch into my base branch.
For future changes, I will make smaller branches and merge them into the base branch

**Comment by JJamesWWang** [comment]
> > Still looks good. This branch is getting a little big on changes; can you start making new branches and merge them to this branch for more refactor-redux work (when applicable)? Makes reviewing a little easier and also more clearer what you are doing.
> 
> I think this is a good idea but if I merge new branches to this one, I won't get features such as CI and code reviews because I am merging into my forked repo: [https://github.com/JiaqiWang18/semesterly/pull/4](https://github.com/JiaqiWang18/semesterly/pull/4)

~~In that case, look at how I added branches to CI previously and make a PR to add this one. I'll approve it and then you can have separate PR.~~

These are two solutions I can think of:
1. Merge this PR and make refactor-frontend-base-branch just be an in-progress branch. Then you can make new PRs.
2. Rebase this branch into a new branch (refactor-redux-base-branch) and add CI to that branch. Then when you are done we merge refactor redux to refactor frontend

Since you are the only one working on refactoring and presumably you are refactoring redux first before moving on to react, the first option seems the easiest with no real consequences. What do you think? Will you do other refactoring work at the same time so that option 2 is better?

**Comment by JiaqiWang18** [comment]
> These are two solutions I can think of:
> 
> 1. Merge this PR and make refactor-frontend-base-branch just be an in-progress branch. Then you can make new PRs.
> 2. Rebase this branch into a new branch (refactor-redux-base-branch) and add CI to that branch. Then when you are done we merge refactor redux to refactor frontend
> 
> Since you are the only one working on refactoring and presumably you are refactoring redux first before moving on to react, the first option seems the easiest with no real consequences. What do you think? Will you do other refactoring work at the same time so that option 2 is better?

Yes, the first option is better since I am mostly working with refactoring redux.

**Comment by JJamesWWang** [comment]
> > These are two solutions I can think of:
> > 
> > 1. Merge this PR and make refactor-frontend-base-branch just be an in-progress branch. Then you can make new PRs.
> > 2. Rebase this branch into a new branch (refactor-redux-base-branch) and add CI to that branch. Then when you are done we merge refactor redux to refactor frontend
> > 
> > Since you are the only one working on refactoring and presumably you are refactoring redux first before moving on to react, the first option seems the easiest with no real consequences. What do you think? Will you do other refactoring work at the same time so that option 2 is better?
> 
> Yes, the first option is better since I am mostly working with refactoring redux.

In that case, fix the merge conflicts and merge this. Then from then on, you can make the PRs more targeted.

**Pull request merged**
