### PR TITLE
Search/Migration:removed 2017-2021 semesters to improve search speeds

### PR DESCRIPTION
**Pull request by jyang0403**
## Description
Removing all older semesters (2017-2021) to improve course search speeds using a new data migration.

## Change Log
Created a new migration file (0042) in timetables/migrations.

### CODE REVIEW

**Comment by JiaqiWang18** [comment]
@jyang0403 So far looks good, you can request a review from James and I when you are ready to merge

**Review by JiaqiWang18 — APPROVED** [review]
The migration looks good! I am just wondering about the load on the database of deleting multiple semesters at once since there are multiple levels of cascade relationships here. Deleting the `Semester` will also delete the `Sections` which then will delete the `Offerings`. @JJamesWWang  what is your take on this?

**Comment by JJamesWWang** [comment]
I think it'll be fine; it's roughly O(n)

**Comment by JJamesWWang** [comment]
You may want to remove the old semesters from the parser too by the way.

**Pull request merged**
