### PR TITLE
Separate instructors in course modal

### PR DESCRIPTION
**Pull request by K02D**
## Before
image

## After
image

### CODE REVIEW

**Review by JJamesWWang — APPROVED** [review]
Looks good, not sure if all instructors will follow this format though. Trying to think of any case where it's not F. Lname

**Review by JJamesWWang — CHANGES_REQUESTED** [review]
Hold on, I don't think this works for names like O'Connor

**Comment by JJamesWWang** [comment]
image

**Comment by JJamesWWang** [comment]
Maybe try to parse based on number of "."'s in the string?

**Comment by K02D** [comment]
Oh yeah sorry. I'll fix it

**Comment by K02D** [comment]
Sorry I couldn't get to this earlier. It should now work for professors that have 3 uppercase letters in their names (M. O'Connor and N. Martinez-Velez) provided the third uppercase letter comes right after a dash (-) or apostrophe (').

Are there any other edge cases I might've missed?

**Comment by JJamesWWang** [comment]
image
Again, I would recommend parsing by number of "."'s in the string, as that appears to be consistent in names

**Comment by K02D** [comment]
Changed. Updated the screenshots on top

**Review by JJamesWWang — APPROVED** [review]
Looks good

**Pull request merged**
