### PR TITLE
Updated graduating class year range & Updated Footers

### PR DESCRIPTION
**Pull request by Boccca2014**
Changed graduating class range from 2017 - 2023 to 2021 - 2027.
Added footers to Press and About pages.

### CODE REVIEW

**Comment by miaboloix** [comment]
Looks like the build is failing with some lint error

**Comment by Boccca2014** [comment]
I ran lint, but it returned no errors. So I ran "npm test -- -u", and I understand that now updated the jest testing. I also ran "npm install" in my docker image, and it seemingly updated the package.json file. Should I maybe revert back to the master branch and redo these changes?

**Comment by miaboloix** [comment]
LGTM!

**Review by miaboloix — DISMISSED** [review]

**Comment by miaboloix** [comment]
> I ran lint, but it returned no errors. So I ran "npm test -- -u", and I understand that now updated the jest testing (I'm unsure if that was a wise move). I also ran "npm install" in my docker container, and it seemingly updated the package.json file. Should I maybe revert back to the master branch and redo these changes?

I would ask Ali about the json file before merging - just to double check!

**Comment by alihacks** [comment]
I would only recommend pushing the new package lock if you intentionally updated package versions and tested that nothing broke otherwise I’d recommend reverting in your branch

**Comment by Boccca2014** [comment]
I didn't intentionally update the package versions, but I ran "npm install" while in my docker container, and it changed the json. I also ran "npm test" and nothing broke. Should I simply remove the change in that json file and keep everything else?

**Review by miaboloix — APPROVED** [review]
LGTM!

**Pull request merged**
