### PR TITLE
Hotfix: update parser to add Spring 2024

### PR DESCRIPTION
**Pull request by JiaqiWang18**
## Description
Spring 2024 course will be available on SIS next week.
This PR updates our course parser that runs daily to fetch and ingest courses for the new semester.

Parser update made according to [this documentation](https://github.com/jhuopensource/semesterly/blob/develop/dev/adding-semesters.md)

### CODE REVIEW

**Comment by JiaqiWang18** [comment]
ignore Backend Linter failure for now: https://github.com/psf/black/issues/3953

**Review by j-wang3 — APPROVED** [review]

**Comment by j-wang3** [comment]
omg this is my roblox github ☠️☠️☠️

**Comment by JiaqiWang18** [comment]
> omg this is my roblox github ☠️☠️☠️

☠️

**Review by K02D — APPROVED** [review]

**Review by jchen324 — APPROVED** [review]
Looks good to me!

**Pull request merged**
