### PR TITLE
Adding tooltip when hovering over icon in timetable drop down

### PR DESCRIPTION
**Pull request by spencerckhuang**
to make it a little easier to see what those buttons do

### CODE REVIEW

**Comment by spencerckhuang** [comment]
there may be a better way to do this... very open to suggestions. i tried using a tooltip similar to in the icon row above the calendar but it ended up being too obstructive. 

maybe an info tab (like ⓘ) you can hover over that makes some modal pop up?

[short demo](https://github.com/jhuopensource/semesterly/assets/112358919/7a83308d-074a-43e4-806c-d39dde0a2b41)

**Comment by JiaqiWang18** [comment]
> there may be a better way to do this... very open to suggestions. i tried using a tooltip similar to in the icon row above the calendar but it ended up being too obstructive.
> 
> maybe an info tab (like ⓘ) you can hover over that makes some modal pop up?
> 
>  timetable-tips-demo.mp4

Suggestion: maybe make the tooltip appear below the icon you clicked on like the icon row above the calendar if doable?
image

**Comment by spencerckhuang** [comment]
> > there may be a better way to do this... very open to suggestions. i tried using a tooltip similar to in the icon row above the calendar but it ended up being too obstructive.
> > maybe an info tab (like ⓘ) you can hover over that makes some modal pop up?
> > timetable-tips-demo.mp4
> 
> Suggestion: maybe make the tooltip appear below the icon you clicked on like the icon row above the calendar if doable? image

Tried this but if you have multiple timetables, the tooltip can sometimes get in the way of you being able to hover over a different button :( I can show you what I mean on Wednesday if we have time

**Comment by JiaqiWang18** [comment]
> > > there may be a better way to do this... very open to suggestions. i tried using a tooltip similar to in the icon row above the calendar but it ended up being too obstructive.
> > > maybe an info tab (like ⓘ) you can hover over that makes some modal pop up?
> > > timetable-tips-demo.mp4
> > 
> > 
> > Suggestion: maybe make the tooltip appear below the icon you clicked on like the icon row above the calendar if doable? image
> 
> Tried this but if you have multiple timetables, the tooltip can sometimes get in the way of you being able to hover over a different button :( I can show you what I mean on Wednesday if we have time

I explored the doc for a bit and if you set the `disableInteractive` flag on `Tooltip` to `true`, it seems to fix this issue.
image
image

**Comment by spencerckhuang** [comment]
> > > > there may be a better way to do this... very open to suggestions. i tried using a tooltip similar to in the icon row above the calendar but it ended up being too obstructive.
> > > > maybe an info tab (like ⓘ) you can hover over that makes some modal pop up?
> > > > timetable-tips-demo.mp4
> > > 
> > > 
> > > Suggestion: maybe make the tooltip appear below the icon you clicked on like the icon row above the calendar if doable? image
> > 
> > 
> > Tried this but if you have multiple timetables, the tooltip can sometimes get in the way of you being able to hover over a different button :( I can show you what I mean on Wednesday if we have time
> 
> I explored the doc for a bit and if you set the `disableInteractive` flag on `Tooltip` to `true`, it seems to fix this issue. image image
you're a goddamn genius

**Review by JiaqiWang18 — APPROVED** [review]

**Pull request merged**
