### PR TITLE
SEM 179 - Upgrade react and dependencies

### PR DESCRIPTION
**Pull request by JiaqiWang18**
### Description - Describe your pull request
upgrade react to 16.14.0 and ensures everything will work

### Checklist
- [x] Upgrad React
- [x] Upgrad other dependencies
- [x] Resolve warnings

### CODE REVIEW

**Comment by JiaqiWang18** [comment]
i deleted the old branch as I found a cleaner way to upgrade react. This is the new PR

**Comment by JiaqiWang18** [comment]
who should be assigned as reviewer?

**Comment by JiaqiWang18** [comment]
be ready for merge, might need review

**Comment by Boccca2014** [comment]
> who should be assigned as reviewer?

Make sure to add me as a reviewer, and don't merge any PRs without my approval! I'll check over this by the end of the week.

**Pull request merged**
