### PR TITLE
Refresh After Submitting Comments

### PR DESCRIPTION
**Pull request by jwfung**
I mostly added a componentDidMount() with a state to trigger the refresh. I'm not sure if this is the best method, but it seems to work :)

### CODE REVIEW

**Review by JJamesWWang — APPROVED** [review]
LGTM

**Review by rbiz4 — CHANGES_REQUESTED** [review]
This still has the old import data button, I'm not sure if it will be overwritten when you merge, but I would appreciate if you could pull cs310 into this branch before you merge :)

**Review by rbiz4 — APPROVED** [review]
Nvm, just realized that this won't be an issue, LGTM

**Comment by miaboloix** [comment]
I would like to see some feedback for the user once they press the + button. I see that the placeholder text 'Type your comment here...' pops right back up once a user hits send. Maybe the feedback could be this placeholder text instead saying "Sending..." or something? Not sure if this will look good but its an idea! Other options could be adding a pop-up, or displaying text somewhere that tells the user things are loading or being processed or something :)

**Review by miaboloix — CHANGES_REQUESTED** [review]
Add some feedback :)

**Comment by JJamesWWang** [comment]
Do you think we could also add a FeatureFlowView that opens up the comments forum that they just commented on? So they click send and then Semester.ly automatically opens up the right comments forum for the right semester instead of having the user click on the right semester again?

**Review by miaboloix — APPROVED** [review]

**Comment by Boccca2014** [comment]
Why is #182 linked with this PR? I press 'x', and it has no effect.

**Pull request merged**
