### PR TITLE
A few grammar fixes and doc simplifications

### PR DESCRIPTION
**Pull request by ottenhoff**
First PR: I learned about this project via the Open Apereo conference last week. The docs are very nice. Here are a few, simple changes.

### CODE REVIEW

**Comment by Boccca2014** [comment]
Hi @ottenhoff, I'll look over this soon, thanks for the contribution! I haven't heard of the Open Apereo conference; it's great to see people recognize our work. 
Is there a link or anything that references when they spoke of our project?

**Comment by ottenhoff** [comment]
https://www.youtube.com/watch?v=7tzctTYhDIc&list=PLu_8PCta0pHecHDijo9W9ExNWF-g24pO3&index=4&t=1230s

**Comment by Boccca2014** [comment]
LGTM 🚀

**Review by Boccca2014 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
