### PR TITLE
Course Modal: Add dark background

### PR DESCRIPTION
**Pull request by JJamesWWang**
## Description
Adds dark mode support for course modal
image
image

Light mode remains unchanged for the most part:

image
image

The x button was hidden (still visible in the images though)

## Change Log
Add modal-header-background to themes
Fix course modal being too large, height wise
Add text-color-thin
Fixes bugs with some items on course modal not disappearing when hovering over lecture section
Added dblue050 and dblue075, which are colors in between dblue0 and dblue1 (dblue1 was determined to be too dark). 050 means 0.5 and 075 means 0.75.

### CODE REVIEW

**Review by K02D — APPROVED** [review]
Looks good

**Comment by JJamesWWang** [comment]
image
@JiaqiWang18 @K02D do either of you know how to change this line break color?

**Comment by JJamesWWang** [comment]
Figured it out, it was border-bottom for the header, and background color in an :after selector for the other sections

**Review by ruibrii — APPROVED** [review]
Looks good

**Pull request merged**
