### PR TITLE
Modify memory and cpu for NGINX.  Reducing replicas for stage env

### PR DESCRIPTION
**Pull request by mike-sellers**
### Tasks
- [ ] 

### Your Checklist
- [ ] Reviewed the [guidelines for contributing?](https://github.com/jhuopensource/semesterly/blob/master/CODE_OF_CONDUCT.md)
- [ ] Linked Issue and/or Project?
- [ ] Added Reviewer, Assignee, and/or Label?

### CODE REVIEW

**Review by JJamesWWang — DISMISSED** [review]
What does this do?

**Comment by mike-sellers** [comment]
> What does this do?

The modifications to the deployment specify resource reservations and constraints, per container, within the AKS cluster.  These resource constraints are tuned to optimize resource consumption and prevent any rogue process from overloading the hosts.  

For deployment, the associated yml files define the pod and services configuration for Kubernetes.

Working with Ali, we are working to optimize cluster resources.

**Comment by JJamesWWang** [comment]
Side note on optimization - The current build seems to be deploying a development version of React rather than a production version. Not sure how much it will improve performance, but I think it's worth mentioning.
image

**Review by alihacks — APPROVED** [review]

**Comment by alihacks** [comment]
> Side note on optimization - The current build seems to be deploying a development version of React rather than a production version. Not sure how much it will improve performance, but I think it's worth mentioning. 

I think this should be doable as a git change. Is it controlled by setting NODE_ENV in the docker build?

**Pull request merged**
