### PR TITLE
Add news-modal

### PR DESCRIPTION
**Pull request by JJamesWWang**
# News Modal
## Description
Currently, Semester.ly users have no built-in way of viewing what updates we are bringing to the site. We would like to add a modal for displaying our recent news, and any updates, such as important deadlines as well.

## Solution
We will create a modal that displays based on a check-for-updates basis. The frontend will receive when the last news update was sent and show if it hasn't been seen yet based on browser storage. These news updates will be submitted through Django's Admin page via a Markdown editor, and the frontend will render this Markdown.

## Change Log
* Created new django app: `notifications`
* Create new model: `NewsUpdate` and registered to admin site.
* Modify model `NewsUpdate` and use `RichTextField` from `ckeditor` for news body
* Create `NewsUpdateView` API endpoint
* Create news modal component
* Add a footer button to show news
* Show/hide modal with a new redux slice

### CODE REVIEW

**Comment by JJamesWWang** [comment]
@JiaqiWang18 @RuiBrian If you update the change log with your changes we can merge this into dev

**Comment by JiaqiWang18** [comment]
> @JiaqiWang18 @RuiBrian If you update the change log with your changes we can merge this into dev

I have updated it

**Review by JJamesWWang — COMMENTED** [review]
I actually can't approve this because I made the PR lol

**Comment by JiaqiWang18** [comment]
Looks Good

**Review by JiaqiWang18 — APPROVED** [review]
Looks Good

**Review by yesterd3v — APPROVED** [review]
LGTM
Definitely a helpful feature

**Review by ruibrii — APPROVED** [review]
Looks good to me

**Pull request merged**
