### PR TITLE
Feature/news modal frontend

### PR DESCRIPTION
**Pull request by ruibrii**
## Description

Implement the frontend for the news modal feature. The modal should only be displayed if the user has not already seen it (this is checked by storing the last-viewed time in local storage) or if the user deliberately clicks the news button located on the footer.

## Change Log

- [x] Create a news modal component
- [x] Fetch news from API endpoint
- [x] Store last-viewed time in local storage and only display news if the user has not seen it
- [x] Style the modal
- [x] Allow a user to see the modal by clicking "news" on the footer

### CODE REVIEW

**Review by JJamesWWang — CHANGES_REQUESTED** [review]
image

Can you make it so that the news modal is accessible by clicking here?

**Review by JiaqiWang18 — APPROVED** [review]
Looks Good!

**Review by JJamesWWang — APPROVED** [review]
Looks good. I made a few tiny changes to fetch data less often and make it look more like Markdown, let me know if it's good and we can merge

**Review by JiaqiWang18 — APPROVED** [review]

**Comment by JJamesWWang** [comment]
@RuiBrian if it looks good you can merge

**Pull request merged**
