### PR TITLE
Added JS Minification

### PR DESCRIPTION
**Pull request by dragonsnapx**
## Description

Added JS Minification: If the environment is production, it will minify the js code. Note that uglifyjs-webpack-plugin must be under 2.x since only 1.x versions are compatible with Webpack 2.

## Change Log

- Package.json: Added uglifyjs-webpack-plugin
- Webpack.config.js: Since the `process.env` argument doesn't seem to work, otherwise it would have been already been minified (and there's no way of testing it in prod), I just put an else statement. The original code does not work.

### CODE REVIEW

**Comment by yesterd3v** [comment]
You need to run [Prettier linter](https://semesterly-v2.readthedocs.io/en/latest/contributing.html?highlight=prettier%20lint#clean-up-changes) before this can be approved. Thanks, Jake!

Make sure to add it to a relevant project, add label, and add James and I as reviewers (on righthand panel) before "opening" PR from a draft.

**Comment by JJamesWWang** [comment]
Hey Jake, is it correct that you can't verify that it works because we would have to deploy to prod to see if it works? 

If so, do you think having it build to the develop site is enough for you to verify whether it works? Or is there some other way we can test it with just the develop pipeline? I want to avoid pushing to prod anything that might not work if possible to avoid potential errors.

**Comment by JiaqiWang18** [comment]
> Hey Jake, is it correct that you can't verify that it works because we would have to deploy to prod to see if it works?
> 
> If so, do you think having it build to the develop site is enough for you to verify whether it works? Or is there some other way we can test it with just the develop pipeline? I want to avoid pushing to prod anything that might not work if possible to avoid potential errors.

I checked the k8s deployment files, and the environment variable `NODE_ENV` is set to `staging` in the `manifests/dev/depoyment.yml` and in `manifests/stage/depoyment.yml`, so we can set those values to `production` to test in the develop site. Or maybe don't change those values because we then need to reapply those deployments, so maybe set `isProd` in webpack config to true if `NODE_ENV` is `staging` or `production`?
`NODE_ENV` is set to `development` for localhost in `docker-compose.yml`, so maybe that is why it isn't minifying in localhost

**Comment by JiaqiWang18** [comment]
> > Hey Jake, is it correct that you can't verify that it works because we would have to deploy to prod to see if it works?
> > If so, do you think having it build to the develop site is enough for you to verify whether it works? Or is there some other way we can test it with just the develop pipeline? I want to avoid pushing to prod anything that might not work if possible to avoid potential errors.
> 
> I checked the k8s deployment files, and the environment variable `NODE_ENV` is set to `staging` in the `manifests/dev/depoyment.yml` and in `manifests/stage/depoyment.yml`, so we can set those values to `production` to test in the develop site.

`NODE_ENV` is set to `development` for localhost in `docker-compose.yml`

**Comment by yesterd3v** [comment]
@dragonsnapx ^

**Comment by dragonsnapx** [comment]
> Hey Jake, is it correct that you can't verify that it works because we would have to deploy to prod to see if it works?
> 
> If so, do you think having it build to the develop site is enough for you to verify whether it works? Or is there some other way we can test it with just the develop pipeline? I want to avoid pushing to prod anything that might not work if possible to avoid potential errors.

Yeah, I think that'll work. Let me know when it's pushed to the dev site!

**Comment by JJamesWWang** [comment]
@dragonsnapx Could you merge develop into your branch/fix the merge conflict so we can merge?

**Comment by dragonsnapx** [comment]
@JJamesWWang 

Yep, merge conflicts should be fixed now.

**Comment by JJamesWWang** [comment]
@JiaqiWang18 if we merge this, will it minify on the dev site or do we need to modify something else too

**Comment by JiaqiWang18** [comment]
> @JiaqiWang18 if we merge this, will it minify on the dev site or do we need to modify something else too

Yes, I believe it should because we are using an `else` statement there so as long as we do not set NODE_ENV to development it should minify. In the dev site, we are setting NODE_ENV to staging. I think we can also test it locally by modifying NODE_ENV to something other than `development` in docker-compose.yml?

**Comment by JiaqiWang18** [comment]
> > @JiaqiWang18 if we merge this, will it minify on the dev site or do we need to modify something else too
> 
> Yes, I believe it should because we are using an `else` statement there so as long as we do not set NODE_ENV to development it should minify. In the dev site, we are setting NODE_ENV to staging. I think we can also test it locally by modifying NODE_ENV to something other than `development` in docker-compose.yml?

I will try it out locally this afternoon

**Review by JJamesWWang — APPROVED** [review]
Will test this out in develop

**Comment by dragonsnapx** [comment]
Working, file size reduced from 4.7MB to a 1.7MB payload in development website. Curiously, looks like JQuery is included twice - in the bundle and from a CDN. Will have to take a look at that.

**Pull request merged**
