### PR TITLE
Advising Dashboard - Invite Advisors Button

### PR DESCRIPTION
**Pull request by Boccca2014**
The goal is implement the "Invite Advisors Modal" for the Comment Forum:
Screen Shot 2021-03-30 at 6 26 57 PM

### CODE REVIEW

**Comment by miaboloix** [comment]
Can you add a description of the goal of this PR + maybe a screenshot of the modal?

**Comment by Boccca2014** [comment]
It's not done yet, but 
Screen Shot 2021-03-30 at 6 26 57 PM

**Comment by Boccca2014** [comment]
It's currently just a modal with no connection to the backend but contains a lot of lines of code and files as it stands now. Perhaps, it's better to merge now, but I could modify the CSS (since it's currently completely incorrect) if necessary before then.

**Comment by Boccca2014** [comment]
This will be redone to follow a similar pattern of shareButton (ShareLink, found in calendar and master_slot).

**Comment by miaboloix** [comment]
So, I looked around and added some styling. I think it should actually be a dropdown instead of a "modal" - the modal component we use is from something called 'boron' - and I think if we kept it a modal we would want to change that grey background (it looks weird with only have the page being added) but I don't actually think it is simple to do that with the package we use.  We could instead toggle the dropdown with a single boolean state variable i believe.

**Comment by Boccca2014** [comment]
Yeah, that makes a lot more sense than keeping it as a modal. I was going to change it to model off of the "share link" button like on the initial page, but I was a bit busy this weekend. Thanks for adding all the css. I'll look further into this very soon and see what else can be added (if there is anything).

**Comment by Boccca2014** [comment]
Current Progress: Converted "Modal" files to typical jsx files. 
Will keep AdvisorRow and add state variable to choose when modal appears. Will use shareLink as reference.

**Pull request closed without merging**
