### PR TITLE
Fix tall letters (p, y, g, etc) having their bottom cut off in search results

### PR DESCRIPTION
**Pull request by K02D**
Before
after

After
after

### CODE REVIEW

**Review by JJamesWWang — CHANGES_REQUESTED** [review]
Causes the lower text to become visible when hovering search results
image

**Comment by JJamesWWang** [comment]
Actually this has nothing to do with your change but can you fix it for us

**Comment by K02D** [comment]
Yeah sure

**Comment by JJamesWWang** [comment]
Create a separate branch for the fix

**Pull request merged**
