### PR TITLE
added chrome stable to yml file

### PR DESCRIPTION
**Pull request by kristinyim**
ChromeDriver issue causing `python manage.py test` to fail. 
General problem with Travis-CI, implemented workaround but track issue here for the long term fix: travis-ci/travis-ci#8836

### CODE REVIEW

**Comment by alihacks** [comment]
I don’t think the failing tests are due to chrome. They are before selenium runs and for parser which doesn’t use chrome. They do pass for me locally and fail on Travis for some reason.

**Comment by kristinyim** [comment]
This fixed the Selenium error on my computer. I'm fixing the python tests error now. I found that 'enrolment' is misspelled in the parser so I'm going to refactor that out.

**Comment by kristinyim** [comment]
Wait are you saying that all the tests pass locally for you? Even the python tests?
The npm tests and lint are fine for me locally but the python test fails.

**Comment by alihacks** [comment]
All the parser tests pass on my setup but 2 of them seem to fail in travis

**Comment by kristinyim** [comment]
On my local, those 2 digest tests fail and I found fixes for both - I'll push when I can. It's weird that they passed on your local, do you have the most recent master code? I think it's failing due to the missing locations PR I pushed a few days ago.

**Comment by alihacks** [comment]
I’m a few commits behind on master. That explains it.

**Comment by kristinyim** [comment]
The python tests work locally. @alihacks can you pull my newest commit and check that they pass for you too? I'm not sure why Travis is failing.

**Comment by alihacks** [comment]
Looks like python tests passed this time.

**Comment by kristinyim** [comment]
Lint and npm tests pass locally, I'm not sure why they're failing on Travis

**Comment by alihacks** [comment]
@kristinyim Turns out there were 2 things installed in travis that didn't need to be (they are in package.json) so when travis was installing them, it was getting latest versions vs. version in package. I removed those 2. And for jest (it's only installed for dev env in package.json) I locked it to version 20 to match that. And tests are passing! 👍

**Pull request merged**
