### PR TITLE
Disable GCal export functionality

### PR DESCRIPTION
**Pull request by miaboloix**
- Google OAuth is failing because we are using the GCal endpoint and we are not authorized to use that endpoint
- While we get the authorization to use the protected endpoint, we are going to disable GCal export so that we can enable Google Login functionality ASAP

### CODE REVIEW

**Review by yesterd3v — DISMISSED** [review]

**Review by JJamesWWang — DISMISSED** [review]
Looks like this messes up the Travis build. Would it be possible to also comment out the tests?

**Review by yesterd3v — APPROVED** [review]

**Comment by JJamesWWang** [comment]
@Boccca2014 do you know if this endpoint was ever granted? can we re-enable gcal?

**Comment by JJamesWWang** [comment]
I'm gonna make this an issue for now and delete the commented out code

**Comment by JJamesWWang** [comment]
@JiaqiWang18 reference this too for commented out code you can delete

**Pull request merged**
