### PR TITLE
Compare Timetables: display common sections first

### PR DESCRIPTION
**Pull request by JiaqiWang18**
## Description
Display common sections first in the sidebar
image

### CODE REVIEW

**Comment by JiaqiWang18** [comment]
hmmm weird that it passes locally

**Comment by JJamesWWang** [comment]
I have no idea why it fails

**Comment by JiaqiWang18** [comment]
> I have no idea why it fails

should be good now

**Review by JJamesWWang — APPROVED** [review]
Looks good

**Pull request merged**
